<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Messages de la page de contact et demandes des écoles et entreprises.
 */
final class Version20260917113224 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Messages de contact';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE contact_message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, subject VARCHAR(20) NOT NULL, name VARCHAR(100) NOT NULL, email VARCHAR(180) NOT NULL, organization VARCHAR(150) DEFAULT NULL, headcount INT DEFAULT NULL, message TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, handled BOOLEAN DEFAULT false NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CONTACT_MESSAGE_HANDLED ON contact_message (handled, created_at)');
        $this->addSql('CREATE INDEX IDX_2C9211FEA76ED395 ON contact_message (user_id)');
        $this->addSql('ALTER TABLE contact_message ADD CONSTRAINT FK_2C9211FEA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE contact_message DROP CONSTRAINT FK_2C9211FEA76ED395');
        $this->addSql('DROP TABLE contact_message');
    }
}
