<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260912191833 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Schéma initial de la plateforme (PostgreSQL).';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE cohort (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(80) NOT NULL, code VARCHAR(40) NOT NULL, active BOOLEAN DEFAULT true NOT NULL, note TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_COHORT_CODE ON cohort (code)');
        $this->addSql('CREATE TABLE exercise_progress (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, files JSON NOT NULL, hints_used INT DEFAULT 0 NOT NULL, xp_earned INT DEFAULT 0 NOT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, track_id VARCHAR(100) NOT NULL, exercise_id VARCHAR(100) NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PROGRESS_EXERCISE ON exercise_progress (user_id, track_id, exercise_id)');
        $this->addSql('CREATE INDEX IDX_246D52AEA76ED395 ON exercise_progress (user_id)');
        $this->addSql('CREATE TABLE feedback (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, handled BOOLEAN DEFAULT false NOT NULL, track_id VARCHAR(100) NOT NULL, exercise_id VARCHAR(100) NOT NULL, kind VARCHAR(255) NOT NULL, message TEXT NOT NULL, hints_used INT DEFAULT 0 NOT NULL, completed BOOLEAN DEFAULT false NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D2294458A76ED395 ON feedback (user_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, display_name VARCHAR(40) NOT NULL, xp INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, cohort_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE INDEX IDX_8D93D64935983C93 ON "user" (cohort_id)');
        $this->addSql('CREATE TABLE waitlist_entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_WAITLIST_EMAIL ON waitlist_entry (email)');
        $this->addSql('ALTER TABLE exercise_progress ADD CONSTRAINT FK_246D52AEA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE feedback ADD CONSTRAINT FK_D2294458A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D64935983C93 FOREIGN KEY (cohort_id) REFERENCES cohort (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE exercise_progress DROP CONSTRAINT FK_246D52AEA76ED395');
        $this->addSql('ALTER TABLE feedback DROP CONSTRAINT FK_D2294458A76ED395');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D64935983C93');
        $this->addSql('DROP TABLE cohort');
        $this->addSql('DROP TABLE exercise_progress');
        $this->addSql('DROP TABLE feedback');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE waitlist_entry');
    }
}
