<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260917094248 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Référencement des parcours : title et description saisis dans l\'admin';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE track_seo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, track_id VARCHAR(100) NOT NULL, seo_title VARCHAR(60) DEFAULT NULL, seo_description VARCHAR(155) DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_TRACK_SEO_TRACK ON track_seo (track_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE track_seo');
    }
}
