<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260928200117 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Connexion avec GitHub : comptes liés (external_identity), et comptes sans mot de passe';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE external_identity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, provider VARCHAR(20) NOT NULL, provider_user_id VARCHAR(64) NOT NULL, username VARCHAR(100) NOT NULL, linked_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EXTERNAL_IDENTITY ON external_identity (provider, provider_user_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_EXTERNAL_IDENTITY_USER ON external_identity (user_id, provider)');
        $this->addSql('CREATE INDEX IDX_85995B37A76ED395 ON external_identity (user_id)');
        $this->addSql('ALTER TABLE external_identity ADD CONSTRAINT FK_85995B37A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ALTER password DROP NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // Échoue tant qu'un compte n'a pas de mot de passe (créé avec GitHub) : à supprimer, ou à doter d'un mot de passe.
        $this->addSql('ALTER TABLE external_identity DROP CONSTRAINT FK_85995B37A76ED395');
        $this->addSql('DROP TABLE external_identity');
        $this->addSql('ALTER TABLE "user" ALTER password SET NOT NULL');
    }
}
