<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Parcours payants : accès aux parcours, tarifs, achats Stripe et journal de ses événements, financement des cohortes.
 * Les cohortes existantes passent en financement « établissement », devis à 0, accès d'un an à compter d'aujourd'hui ;
 * leurs apprenants reçoivent leurs accès avec la commande app:acces:initialiser (qui lit les parcours des packs).
 */
final class Version20260917050113 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Parcours payants : accès, tarifs, achats, événements Stripe, financement des cohortes';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE purchase (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, customer_email VARCHAR(180) NOT NULL, status VARCHAR(20) NOT NULL, amount_paid INT DEFAULT NULL, stripe_session_id VARCHAR(255) DEFAULT NULL, stripe_payment_intent_id VARCHAR(255) DEFAULT NULL, receipt_url TEXT DEFAULT NULL, withdrawal_waiver_text TEXT NOT NULL, withdrawal_waiver_accepted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, paid_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, refunded_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, stripe_refund_id VARCHAR(255) DEFAULT NULL, track_id VARCHAR(100) NOT NULL, price INT NOT NULL, price_kind VARCHAR(20) NOT NULL, user_id INT DEFAULT NULL, cohort_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_PURCHASE_TRACK_STATUS ON purchase (track_id, status)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PURCHASE_STRIPE_SESSION ON purchase (stripe_session_id)');
        $this->addSql('CREATE INDEX IDX_6117D13BA76ED395 ON purchase (user_id)');
        $this->addSql('CREATE INDEX IDX_6117D13B35983C93 ON purchase (cohort_id)');
        $this->addSql('CREATE TABLE stripe_event (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, received_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, processed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deliveries INT DEFAULT 1 NOT NULL, error TEXT DEFAULT NULL, event_id VARCHAR(255) NOT NULL, type VARCHAR(100) NOT NULL, payload TEXT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_STRIPE_EVENT ON stripe_event (event_id)');
        $this->addSql('CREATE TABLE track_access (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, note VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, track_id VARCHAR(100) NOT NULL, source VARCHAR(20) NOT NULL, starts_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ends_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, cohort_id INT DEFAULT NULL, purchase_id INT DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_TRACK_ACCESS_USER_TRACK ON track_access (user_id, track_id)');
        $this->addSql('CREATE INDEX IDX_4EABEABD35983C93 ON track_access (cohort_id)');
        $this->addSql('CREATE INDEX IDX_4EABEABD558FBEB9 ON track_access (purchase_id)');
        $this->addSql('CREATE INDEX IDX_4EABEABDA76ED395 ON track_access (user_id)');
        $this->addSql('CREATE TABLE track_pricing (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, track_id VARCHAR(100) NOT NULL, normal_price INT DEFAULT 0 NOT NULL, founder_price INT DEFAULT NULL, founder_active BOOLEAN DEFAULT false NOT NULL, founder_ends_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, founder_quota_max INT DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_TRACK_PRICING_TRACK ON track_pricing (track_id)');
        $this->addSql('ALTER TABLE purchase ADD CONSTRAINT FK_6117D13BA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase ADD CONSTRAINT FK_6117D13B35983C93 FOREIGN KEY (cohort_id) REFERENCES cohort (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE track_access ADD CONSTRAINT FK_4EABEABD35983C93 FOREIGN KEY (cohort_id) REFERENCES cohort (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE track_access ADD CONSTRAINT FK_4EABEABD558FBEB9 FOREIGN KEY (purchase_id) REFERENCES purchase (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE track_access ADD CONSTRAINT FK_4EABEABDA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cohort ADD funding_mode VARCHAR(20) DEFAULT \'institution\' NOT NULL');
        // Cohortes existantes : accès d'un an à partir d'aujourd'hui, effectif prévu = effectif actuel, devis à 0.
        $this->addSql('ALTER TABLE cohort ADD access_starts_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE cohort ADD access_ends_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE cohort ADD expected_headcount INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE cohort ADD learner_price INT DEFAULT NULL');
        $this->addSql('ALTER TABLE cohort ADD quote_amount INT DEFAULT NULL');
        $this->addSql("UPDATE cohort SET access_starts_at = CURRENT_DATE, access_ends_at = CURRENT_DATE + INTERVAL '1 year', quote_amount = 0, expected_headcount = (SELECT COUNT(*) FROM \"user\" u WHERE u.cohort_id = cohort.id)");
        $this->addSql('ALTER TABLE cohort ALTER access_starts_at SET NOT NULL');
        $this->addSql('ALTER TABLE cohort ALTER access_ends_at SET NOT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE purchase DROP CONSTRAINT FK_6117D13BA76ED395');
        $this->addSql('ALTER TABLE purchase DROP CONSTRAINT FK_6117D13B35983C93');
        $this->addSql('ALTER TABLE track_access DROP CONSTRAINT FK_4EABEABD35983C93');
        $this->addSql('ALTER TABLE track_access DROP CONSTRAINT FK_4EABEABD558FBEB9');
        $this->addSql('ALTER TABLE track_access DROP CONSTRAINT FK_4EABEABDA76ED395');
        $this->addSql('DROP TABLE purchase');
        $this->addSql('DROP TABLE stripe_event');
        $this->addSql('DROP TABLE track_access');
        $this->addSql('DROP TABLE track_pricing');
        $this->addSql('ALTER TABLE cohort DROP funding_mode');
        $this->addSql('ALTER TABLE cohort DROP access_starts_at');
        $this->addSql('ALTER TABLE cohort DROP access_ends_at');
        $this->addSql('ALTER TABLE cohort DROP expected_headcount');
        $this->addSql('ALTER TABLE cohort DROP learner_price');
        $this->addSql('ALTER TABLE cohort DROP quote_amount');
    }
}
